name: Pyright Lint

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - "sora/**"
      - "tests/**"

jobs:
  pyright:
    name: Pyright Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python environment
        uses: ./.github/actions/setup-python

      - run: echo "$(pdm venv --path in-project)" >> $GITHUB_PATH

      - name: Run Pyright
        uses: jakebailey/pyright-action@v1
